package me.zodiakk.spigotjs.engine.object;

public interface JsPlayer extends JsOfflinePlayer, JsLivingEntity {
    public void chat(String message);
    public boolean getAllowFlight();
    public JsLocation getCompassTarget();
    public String getDisplayName();
    public Number getExhaustion();
    public Number getExp();
    public Number getFlySpeed();
    public Number getFoodLevel();
    public Number getHealthScale();
    public Number getLevel();
    public String getListName();
    public Number getPlayerTime();
    public Number getPlayerTimeOffset();
    public String getPlayerWeather();
    public Number getSaturation();
    public Number getTotalExperience();
    public Number getWalkSpeed();
    public void giveExp(Number amount);
    public void giveExpLevels(Number levels);
    public boolean isFlying();
    public boolean isHealthScaled();
    public boolean isPlayerTimeRelative();
    public boolean isSneaking();
    public boolean isSprinting();
    public void kick(String reason);
    public void runCommand(String command);
    public void playSound(String sound, Number volume, Number pitch);
    public void playSound(String sound, Number volume, Number pitch, JsLocation location);
    public void resetPlayerTime();
    public void sendMessage(String message);
    public void sendMessage(String[] messages);
    public void setAllowFlight(Boolean allowFlight);
    public void setBedSpawnLocation(JsLocation location);
    public void setCompassTarget(JsLocation location);
    public void setDisplayName(String displayName);
    public void setExhaustion(Number value);
    public void setExp(Number exp);
    public void setFlying(Boolean flying);
    public void setFlySpeed(Number flySpeed);
    public void setFoodLevel(Number foodLevel);
    public void setHealthScale(Number healthScale);
    public void setHealthScaled(Boolean healthScaled);
    public void setLevel(Number level);
    public void setPlayerListName(String name);
    public void setPlayerTime(Number time, Boolean relative);
    public void setPlayerWeather(String weather);
    public void setSaturation(Number saturation);
    public void setSneaking(Boolean sneaking);
    public void setSprinting(Boolean sprinting);
    public void setTotalExperience(Number totalExperience);
    public void setWalkSpeed(Number walkSpeed);
    public void closeInventory();
    public JsItemStack[] getEnderChest();
    public String getGameMode();
    public JsItemStack[] getInventory();
    public JsItemStack getItemInMainHand();
    public JsItemStack getItemInOffHand();
    public JsItemStack getItemOnCursor();
    public boolean isBlocking();
    public boolean isSleeping();
    public void setEnderChest(JsItemStack[] items);
    public void setGameMode(String gameMode);
    public void setInventory(JsItemStack[] items);
    public void setItemInMainHand(JsItemStack item);
    public void setItemInOffHand(JsItemStack item);
    public boolean hasPermission(String permission);
}
