package me.zodiakk.spigotjs.engine.object;

public interface Player extends OfflinePlayer, LivingEntity {
    public void awardAchievement(String achievement);
    public void chat(String message);
    public boolean getAllowFlight();
    public Location getCompassTarget();
    public String getDisplayName();
    public Number getExhaustion();
    public Number getExp();
    public Number getFlySpeed();
    public Number getFoodLevel();
    public Number getHealthScale();
    public Number getLevel();
    public String getListName();
    public Number getPlayerTime();
    public Number getPlayerTimeOffset();
    public String getPlayerWeather();
    public Number getSaturation();
    public Number getTotalExperience();
    public Number getWalkSpeed();
    public void giveExp(Number amount);
    public void giveExpLevels(Number levels);
    public boolean hasAchievement(String achievement);
    public boolean isFlying();
    public boolean isHealthScaled();
    public boolean isPlayerTimeRelative();
    public boolean isSneaking();
    public boolean isSprinting();
    public void kick(String reason);
    public void execute(String command);
    public void playSound(String sound, Number volume, Number pitch);
    public void playSound(String sound, Number volume, Number pitch, Location location);
    public void removeAchievement(String achievement);
    public void resetPlayerTime();
    public void sendMessage(String message);
    public void sendMessage(String[] messages);
    public void setAllowFlight(boolean allowFlight);
    public void setBedSpawnLocation(Location location);
    public void setCompassTarget(Location location);
    public void setDisplayName(String displayName);
    public void setExhaustion(Number value);
    public void setExp(Number exp);
    public void setFlying(boolean flying);
    public void setFlySpeed(Number flySpeed);
    public void setFoodLevel(Number foodLevel);
    public void setHealthScale(Number healthScale);
    public void setHealthScaled(boolean healthScaled);
    public void setLevel(Number level);
    public void setPlayerListName(String name);
    public void setPlayerTime(Number time, boolean relative);
    public void setPlayerWeather(String weather);
    public void setSaturation(Number saturation);
    public void setSneaking(boolean sneaking);
    public void setSprinting(boolean sprinting);
    public void setTotalExperience(Number totalExperience);
    public void setWalkSpeed(Number walkSpeed);
    public void closeInventory();
    public ItemStack[] getEnderChest();
    public String getGameMode();
    public ItemStack[] getInventory();
    public ItemStack getItemInMainHand();
    public ItemStack getItemInOffHand();
    public ItemStack getItemOnCursor();
    public boolean isBlocking();
    public boolean isSleeping();
    public void setEnderChest(ItemStack[] items);
    public void setGameMode(String gameMode);
    public void setInventory(ItemStack[] items);
    public void setItemInMainHand(ItemStack item);
    public void setItemInOffHand(ItemStack item);
    public boolean hasPermission(String permission);
}
